# Railway 部署配置
[build]
  builder = "NIXPACKS"

[deploy]
  startCommand = "npm run start:all"
  healthcheckPath = "/"
  
[variables]
  NODE_VERSION = "18"
  NPM_CONFIG_PRODUCTION = "false"
  PORT = "3000"
  SIGNALING_PORT = "3002"
